spring.application.name=marc-qr
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=3MB
spring.thymeleaf.cache=true
server.port=${PORT:8080}
server.error.whitelabel.enabled=false
server.error.include-message=never
server.compression.enabled=true
server.compression.mime-types=text/html,text/css,application/javascript,application/json,image/svg+xml
